# -*- coding: utf-8 -*-
"""Proyecto 2 Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKLkdVq7BJIZcxVL4ol6BLxEV9yJUd5u

**Bloque 0 y 1**
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

try:
    import umap
except ImportError:
    !pip install -q umap-learn
    import umap

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE


plt.rcParams.update({
    'font.size': 14,
    'axes.labelsize': 14,
    'axes.titlesize': 15,
    'xtick.labelsize': 14,
    'ytick.labelsize': 14,
    'legend.fontsize': 14
})

registro_tiempos = []

print("Cargando conjuntos de datos eco-acústicos...")
train_df = pd.read_csv('eco_acoustic_train.csv')
test_df = pd.read_csv('eco_acoustic_test.csv')

mel_cols = [f'mel_{i}' for i in range(64)]
X_train = train_df[mel_cols].values
y_train = train_df['species_id'].values

scaler = StandardScaler() #zscore
X_train_scaled = scaler.fit_transform(X_train)


np.save('X_train_scaled_checkpoint.npy', X_train_scaled)
np.save('y_train_checkpoint.npy', y_train)
print(f" Checkpoint guardado para el grupo. Dimensiones: {X_train_scaled.shape}")

X_test = test_df[mel_cols].values
y_test = test_df['species_id'].values
X_test_scaled = scaler.transform(X_test)

np.save('X_test_scaled_checkpoint.npy', X_test_scaled)
np.save('y_test_checkpoint.npy', y_test)
print(f" Checkpoint de test guardado. Dimensiones: {X_test_scaled.shape}")

# eda
print("\n Generando visualizaciones del perfil estadístico (EDA)...")


plt.figure(figsize=(7, 4.5))
sns.countplot(x=train_df['species_id'], palette='viridis')
plt.title("Distribución de Frecuencias de Clases Faunísticas")
plt.xlabel("Species ID")
plt.ylabel("Número de Muestras")
plt.tight_layout()
plt.show()

# boxplot de dispersión de coeficientes Mel
plt.figure(figsize=(10, 5))
features_preview = pd.DataFrame(X_train_scaled[:, :6], columns=[f'mel_{i}' for i in range(6)])
features_preview['species_id'] = y_train
melted_eda = pd.melt(features_preview, id_vars='species_id', var_name='Bandas Mel', value_name='Magnitud Z-score')
sns.boxplot(x='Bandas Mel', y='Magnitud Z-score', hue='species_id', data=melted_eda, palette='Set2')
plt.title("Análisis de Dispersión Tímbrica por Especie")
plt.tight_layout()
plt.show()

#pca
print("\n Calculando espectro de varianza acumulada para PCA...")
pca_full = PCA().fit(X_train_scaled)
var_cum = np.cumsum(pca_full.explained_variance_ratio_) * 100
k_95 = np.argmax(var_cum >= 95) + 1

plt.figure(figsize=(7.5, 4.5))
plt.plot(range(1, len(var_cum) + 1), var_cum, 'o-', color='#003087', linewidth=2, markersize=4)
plt.axhline(95, color='red', linestyle='--', label=f'Umbral 95% ({k_95} PCs)')
plt.title("Varianza Explicada Acumulada — Espacio Mel")
plt.xlabel("Componentes Principales")
plt.ylabel("Varianza Retenida")
plt.legend(loc='lower right')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Se decidió clusterizar sobre el espacio PCA que retiene el 95% de la varianza (k_95 componentes) en ve de las 64D originales
print(f"\n  Exportando proyección PCA-{k_95} para el bloque de clustering...")
pca_k = PCA(n_components=k_95, random_state=42)
X_train_pca = pca_k.fit_transform(X_train_scaled)
var_pca_k = pca_k.explained_variance_ratio_.sum() * 100

np.save('X_train_pca_checkpoint.npy', X_train_pca)
print(f"Checkpoint PCA-{k_95} guardado. Dims: {X_train_pca.shape} "
      f"({var_pca_k:.1f}% varianza retenida)")

# proyección pca 2D
labels_fauna = ['Especie 10', 'Especie 12', 'Especie 17', 'Especie 18', 'Especie 23']
print("\n Proyectando espacio Mel en 2D mediante PCA lineal...")
t_start = time.time()
pca_2d = PCA(n_components=2)
Z_pca = pca_2d.fit_transform(X_train_scaled)
t_pca = time.time() - t_start
var_pca_2d = pca_2d.explained_variance_ratio_.sum() * 100

plt.figure(figsize=(7.5, 6))
sc_pca = plt.scatter(Z_pca[:, 0], Z_pca[:, 1], c=y_train, cmap='tab10', s=12, alpha=0.7)
plt.title(f"Proyección PCA 2D — Espacio Mel ({t_pca:.1f}s)")
plt.xlabel("Componente Principal 1")
plt.ylabel("Componente Principal 2")
plt.legend(handles=sc_pca.legend_elements()[0], labels=labels_fauna,
           loc='best', title="Especie")
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()

registro_tiempos.append({
    'Método': 'PCA (2D)',
    'Tipo': 'Lineal',
    'Tiempo (s)': round(t_pca, 2),
    'Métrica de retención': f'{var_pca_2d:.1f}% varianza global (2 PCs)'
})

# barrido de hiperparametros tsne
print("\n Iniciando barrido analítico de perplejidades en t-SNE...")
perplexities = [5, 30, 80]
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for idx, perp in enumerate(perplexities):
    t_start = time.time()
    tsne_mod = TSNE(n_components=2, perplexity=perp, random_state=42, n_jobs=-1)
    Z_tsne = tsne_mod.fit_transform(X_train_scaled)
    t_exec = time.time() - t_start

    sc = axes[idx].scatter(Z_tsne[:, 0], Z_tsne[:, 1], c=y_train, cmap='tab10', s=12, alpha=0.7)
    axes[idx].set_title(f"Perplexity = {perp} ({t_exec:.1f}s)")
    axes[idx].set_xlabel("Dimensión 1")
    if idx == 0: axes[idx].set_ylabel("Dimensión 2")
    if perp == 30:
        registro_tiempos.append({
            'Método': 't-SNE (perp=30)',
            'Tipo': 'No lineal (manifold)',
            'Tiempo (s)': round(t_exec, 2),
            'Métrica de retención': 'Distancias locales (vecindades)'})
fig.legend(handles=sc.legend_elements()[0], labels=labels_fauna, loc='lower center', ncol=5, bbox_to_anchor=(0.5, -0.08))
plt.tight_layout()
plt.show()

# hiperparametros umap
print("\n Iniciando barrido hiperparamétrico cruzado en UMAP...")
neighbors_list = [5, 30]
min_dist_list = [0.01, 0.5]
fig, axes = plt.subplots(2, 2, figsize=(13, 11))

idx_ax = 0
for nn in neighbors_list:
    for md in min_dist_list:
        row, col = divmod(idx_ax, 2)
        t_start = time.time()
        umap_mod = umap.UMAP(n_components=2, n_neighbors=nn, min_dist=md, random_state=42)
        Z_umap = umap_mod.fit_transform(X_train_scaled)
        t_exec = time.time() - t_start
        if nn == 30 and md == 0.5:
            registro_tiempos.append({
                'Método': 'UMAP (nn=30, md=0.5)',
                'Tipo': 'No lineal (manifold)',
                'Tiempo (s)': round(t_exec, 2),
                'Métrica de retención': 'Estructura local + global'})

        sc_u = axes[row, col].scatter(Z_umap[:, 0], Z_umap[:, 1], c=y_train, cmap='tab10', s=10, alpha=0.7)
        axes[row, col].set_title(f"n_neighbors={nn}, min_dist={md} ({t_exec:.1f}s)")
        axes[row, col].set_xlabel("Dimensión 1")
        axes[row, col].set_ylabel("Dimensión 2")
        idx_ax += 1

fig.legend(handles=sc_u.legend_elements()[0], labels=labels_fauna, loc='lower center', ncol=5, bbox_to_anchor=(0.5, -0.02))
plt.tight_layout()
plt.show()

print("\n Reporte cuantitativo comparativo de métodos de reducción:\n")
tabla_reduccion = pd.DataFrame(registro_tiempos)
tabla_reduccion = tabla_reduccion[['Método', 'Tipo', 'Tiempo (s)', 'Métrica de retención']]
print(tabla_reduccion.to_string(index=False))

"""BLOQUE 2"""

from sklearn.cluster import DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import (silhouette_score, davies_bouldin_score,
                             adjusted_rand_score)
X_train_pca = np.load('X_train_pca_checkpoint.npy')
y_train      = np.load('y_train_checkpoint.npy')

from sklearn.decomposition import PCA
X_train_scaled = np.load('X_train_scaled_checkpoint.npy')
Z_pca = PCA(n_components=2, random_state=42).fit_transform(X_train_scaled)

labels_fauna = ['Especie 10', 'Especie 12', 'Especie 17', 'Especie 18', 'Especie 23']
print(f"Espacio de clustering: {X_train_pca.shape}  |  Espacio de gráfico: {Z_pca.shape}")

min_samples = 2 * X_train_pca.shape[1]
print(f"min_samples = {min_samples} (heurística 2*dim)")

nn = NearestNeighbors(n_neighbors=min_samples).fit(X_train_pca)
distances, _ = nn.kneighbors(X_train_pca)
k_dist = np.sort(distances[:, -1])

x = np.arange(len(k_dist))
x1, y1, x2, y2 = x[0], k_dist[0], x[-1], k_dist[-1]
numer = np.abs((y2 - y1) * x - (x2 - x1) * k_dist + x2 * y1 - y2 * x1)
denom = np.hypot(y2 - y1, x2 - x1)
eps_idx = np.argmax(numer / denom)
eps_est = k_dist[eps_idx]
print(f" eps estimado en el codo = {eps_est:.3f}")

plt.figure(figsize=(7.5, 4.5))
plt.plot(k_dist, color='#003087', linewidth=2)
plt.axhline(eps_est, color='red', linestyle='--',
            label=f'eps (codo) = {eps_est:.2f}')
plt.axvline(eps_idx, color='gray', linestyle=':', alpha=0.7)
plt.title(f"k-distance plot (k = {min_samples})")
plt.xlabel("Puntos ordenados por distancia")
plt.ylabel(f"Distancia al {min_samples}º vecino")
plt.legend(loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

print("Barrido de eps alrededor del valor estimado:\n")
barrido_db = []
for factor in [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]:
    eps = eps_est * factor
    lab = DBSCAN(eps=eps, min_samples=min_samples).fit(X_train_pca).labels_
    n_cl = len(set(lab)) - (1 if -1 in lab else 0)
    n_noise = int((lab == -1).sum())
    barrido_db.append({'eps': round(eps, 2), 'clusters': n_cl, 'ruido': n_noise, 'ruido_%': round(100*n_noise/len(lab), 1)})
print(pd.DataFrame(barrido_db).to_string(index=False))

dbscan = DBSCAN(eps=eps_est, min_samples=min_samples).fit(X_train_pca)
labels_dbscan = dbscan.labels_
n_clusters_db = len(set(labels_dbscan)) - (1 if -1 in labels_dbscan else 0)
n_noise_db = int((labels_dbscan == -1).sum())
print(f"\n DBSCAN final -> clusters = {n_clusters_db} | " f"ruido = {n_noise_db} ({100*n_noise_db/len(labels_dbscan):.1f}%)")

# gaussian mixture model (paradigma probabilístico)
# n_components mediante BIC y AIC
n_range = range(2, 9)
bics, aics = [], []
print("Barrido de componentes para GMM (BIC / AIC):\n")
for n in n_range:
    gmm_tmp = GaussianMixture(n_components=n, covariance_type='full',
                              random_state=42, n_init=2).fit(X_train_pca)
    bics.append(gmm_tmp.bic(X_train_pca))
    aics.append(gmm_tmp.aic(X_train_pca))
    print(f"    n={n}:  BIC={bics[-1]:.0f}   AIC={aics[-1]:.0f}")

best_n = list(n_range)[int(np.argmin(bics))]
print(f"\nn_components óptimo (mínimo BIC) = {best_n}")

plt.figure(figsize=(7.5, 4.5))
plt.plot(list(n_range), bics, 'o-', label='BIC', color='#003087', linewidth=2)
plt.plot(list(n_range), aics, 's--', label='AIC', color='#C1272D', linewidth=2)
plt.axvline(best_n, color='gray', linestyle=':', label=f'Óptimo (n={best_n})')
plt.title("Selección de componentes GMM — BIC vs AIC")
plt.xlabel("Número de componentes")
plt.ylabel("Criterio de información")
plt.legend(loc='best')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

gmm = GaussianMixture(n_components=best_n, covariance_type='full', # ajuste final del gmm con el número óptimo de componentes
                      random_state=42, n_init=2).fit(X_train_pca)
labels_gmm = gmm.predict(X_train_pca)
print(f"GMM ajustado con {best_n} componentes ")
print(f"    Distribución de puntos por componente:")
print(pd.Series(labels_gmm).value_counts().sort_index().to_string())

# validación intenrea
def metricas_internas(X, labels):
    mask = labels != -1
    etiquetas_validas = set(labels[mask])
    if len(etiquetas_validas) < 2:
        return float('nan'), float('nan')
    sil = silhouette_score(X[mask], labels[mask])
    db = davies_bouldin_score(X[mask], labels[mask])
    return sil, db

sil_db, dbi_db = metricas_internas(X_train_pca, labels_dbscan)
sil_gmm, dbi_gmm = metricas_internas(X_train_pca, labels_gmm)

# Validación externa
ari_db = adjusted_rand_score(y_train, labels_dbscan)
ari_gmm = adjusted_rand_score(y_train, labels_gmm)

tabla_metricas = pd.DataFrame([
    {'Modelo': 'DBSCAN', 'N° clusters': n_clusters_db,
     'Silhouette': round(sil_db, 3), 'Davies-Bouldin': round(dbi_db, 3),
     'ARI vs especies': round(ari_db, 3)},
    {'Modelo': 'GMM', 'N° clusters': best_n,
     'Silhouette': round(sil_gmm, 3), 'Davies-Bouldin': round(dbi_gmm, 3),
     'ARI vs especies': round(ari_gmm, 3)},])
print("Comparativa de validación de clustering:\n")
print(tabla_metricas.to_string(index=False))

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

mask_noise = labels_dbscan == -1
axes[0].scatter(Z_pca[~mask_noise, 0], Z_pca[~mask_noise, 1],
                c=labels_dbscan[~mask_noise], cmap='tab10', s=12, alpha=0.7)
axes[0].scatter(Z_pca[mask_noise, 0], Z_pca[mask_noise, 1],
                c='lightgray', s=10, alpha=0.5, label='Ruido')
axes[0].set_title(f"DBSCAN (eps={eps_est:.2f}, clusters={n_clusters_db})")
axes[0].set_xlabel("Componente Principal 1")
axes[0].set_ylabel("Componente Principal 2")
axes[0].legend(loc='best')

axes[1].scatter(Z_pca[:, 0], Z_pca[:, 1],
                c=labels_gmm, cmap='tab10', s=12, alpha=0.7)
axes[1].set_title(f"GMM (n_components={best_n})")
axes[1].set_xlabel("Componente Principal 1")
axes[1].set_ylabel("Componente Principal 2")

plt.tight_layout()
plt.savefig('clustering_proyeccion.png', dpi=150, bbox_inches='tight')
plt.show()

np.save('labels_dbscan_checkpoint.npy', labels_dbscan)
np.save('labels_gmm_checkpoint.npy', labels_gmm)
print("Etiquetas de clustering exportadas:")
print("  labels_dbscan_checkpoint.npy")
print("  labels_gmm_checkpoint.npy")

"""BLOQUE 3"""

import numpy as np
import pandas as pd
import torch

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

print("BLOQUE 3 - PREPROCESAMIENTO PARA CLASIFICACIÓN")

# Selección de las variables

mel_cols = [f"mel_{i}" for i in range(64)]

X_train = train_df[mel_cols].values
X_test = test_df[mel_cols].values

y_train = train_df["species_id"].values
y_test = test_df["species_id"].values

print("\nDimensiones originales")

print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

# Escalamiento

print("\nAplicando StandardScaler...")

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

print("Escalamiento finalizado.")

# Codificacion de etiquetas

print("\nCodificando etiquetas...")

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)

y_test_encoded = label_encoder.transform(y_test)

num_classes = len(label_encoder.classes_)

print(f"Número de clases: {num_classes}")

print("\nCorrespondencia de clases")

for original, nueva in zip(
    label_encoder.classes_,
    label_encoder.transform(label_encoder.classes_)
):
    print(f"{original}  --->  {nueva}")

# tensores

print("\nConvirtiendo a tensores PyTorch...")

X_train_tensor = torch.tensor(
    X_train_scaled,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test_scaled,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train_encoded,
    dtype=torch.long
)

y_test_tensor = torch.tensor(
    y_test_encoded,
    dtype=torch.long
)

print("Conversión completada.")



train_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor
)

test_dataset = TensorDataset(
    X_test_tensor,
    y_test_tensor
)

print("\nTensorDataset creado correctamente.")



BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

print(f"Batch Size: {BATCH_SIZE}")



print("\nVerificando DataLoader...")

for X_batch, y_batch in train_loader:

    print("Batch de características :", X_batch.shape)

    print("Batch de etiquetas       :", y_batch.shape)

    break


device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("\nDispositivo de entrenamiento")

print(device)

##Resumen

print("\n" + "="*50)

print("RESUMEN DEL BLOQUE 3")

print("="*50)

print(f"Número de muestras de entrenamiento : {len(train_dataset)}")

print(f"Número de muestras de prueba        : {len(test_dataset)}")

print(f"Número de variables                : {X_train.shape[1]}")

print(f"Número de clases                   : {num_classes}")

print(f"Batch Size                         : {BATCH_SIZE}")

print(f"Dispositivo                        : {device}")

print("="*70)

print("Bloque 3 finalizado correctamente.")

import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from torch.utils.data import TensorDataset, DataLoader

print("BLOQUE 3 - PREPROCESAMIENTO PARA CLASIFICACIÓN")

train_df = pd.read_csv('eco_acoustic_train.csv')
test_df = pd.read_csv('eco_acoustic_test.csv')

mel_cols = [f"mel_{i}" for i in range(64)]

X_train = train_df[mel_cols].values
X_test = test_df[mel_cols].values

y_train = train_df["species_id"].values
y_test = test_df["species_id"].values

print("Dimensiones del dataset")
print("Train:", X_train.shape)
print("Test:", X_test.shape)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

plt.figure(figsize=(12,4))
plt.subplot(1,2,1)
sns.boxplot(data=pd.DataFrame(X_train[:,:10]))
plt.title("Distribución original (10 bandas Mel)")

plt.subplot(1,2,2)
sns.boxplot(data=pd.DataFrame(X_train_scaled[:,:10]))
plt.title("Distribución escalada (Z-score)")
plt.tight_layout()
plt.show()

print("\nInterpretación:")
print("El escalamiento centra los datos en media 0 y varianza 1.")
print("Esto mejora el rendimiento de modelos como MLP al evitar sesgos por magnitud.")

corr = np.corrcoef(X_train_scaled.T)

plt.figure(figsize=(8,6))
sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Correlación entre bandas Mel (normalizadas)")
plt.show()

print("\nInterpretación:")
print("La matriz muestra relaciones entre frecuencias Mel.")
print("Correlaciones altas indican redundancia espectral.")
print("Esto justifica reducción dimensional (PCA en Bloque 1).")

label_encoder = LabelEncoder()
y_train_enc = label_encoder.fit_transform(y_train)
y_test_enc = label_encoder.transform(y_test)

plt.figure(figsize=(7,4))
sns.countplot(x=y_train)
plt.title("Distribución de clases (species_id)")
plt.xticks(rotation=45)
plt.show()

print("\nInterpretación:")
print("Se observa el balance de clases.")
print("Desbalance puede afectar el entrenamiento del MLP (bias hacia clases dominantes).")

X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train_enc, dtype=torch.long)
y_test_tensor = torch.tensor(y_test_enc, dtype=torch.long)

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

BATCH_SIZE = 64

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("\nResumen del preprocesamiento")
print("Train:", X_train_tensor.shape)
print("Test:", X_test_tensor.shape)
print("Clases:", len(label_encoder.classes_))
print("Batch size:", BATCH_SIZE)
print("Device:", device)

"""Bloque 4"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_tensor, y_train_tensor,
    test_size=0.2,
    random_state=42,
    stratify=y_train_tensor
)

input_dim = X_train_tensor.shape[1]
num_classes = len(torch.unique(y_train_tensor))


class MLP(nn.Module):
    def __init__(self, dropout=0.0, batchnorm=False):
        super().__init__()

        layers = []

        layers.append(nn.Linear(input_dim, 256))
        if batchnorm:
            layers.append(nn.BatchNorm1d(256))
        layers.append(nn.ReLU())
        if dropout > 0:
            layers.append(nn.Dropout(dropout))

        layers.append(nn.Linear(256, 128))
        if batchnorm:
            layers.append(nn.BatchNorm1d(128))
        layers.append(nn.ReLU())
        if dropout > 0:
            layers.append(nn.Dropout(dropout))

        layers.append(nn.Linear(128, 64))
        layers.append(nn.ReLU())

        layers.append(nn.Linear(64, num_classes))

        self.model = nn.Sequential(*layers)

    def forward(self, x):
        return self.model(x)


def train_model(model, epochs=25, lr=0.001):

    model = model.to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    history = {
        "loss": [],
        "val_loss": [],
        "acc": [],
        "val_acc": []
    }

    for epoch in range(epochs):

        model.train()

        train_loss = 0
        correct = 0
        total = 0

        for X, y in train_loader:

            X, y = X.to(device), y.to(device)

            optimizer.zero_grad()

            outputs = model(X)

            loss = criterion(outputs, y)

            loss.backward()

            optimizer.step()

            train_loss += loss.item()

            preds = torch.argmax(outputs, 1)

            correct += (preds == y).sum().item()

            total += y.size(0)

        train_acc = correct / total
        train_loss = train_loss / len(train_loader)

        model.eval()

        val_loss = 0
        val_correct = 0
        val_total = 0

        with torch.no_grad():

            for i in range(len(X_val)):

                x = X_val[i].unsqueeze(0).to(device)
                y = y_val[i].unsqueeze(0).to(device)

                out = model(x)

                loss = criterion(out, y)

                val_loss += loss.item()

                pred = torch.argmax(out, 1)

                val_correct += (pred == y).sum().item()

                val_total += 1

        val_acc = val_correct / val_total
        val_loss = val_loss / len(X_val)

        history["loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1}/{epochs} | Loss {train_loss:.4f} | Acc {train_acc:.4f} | Val Loss {val_loss:.4f} | Val Acc {val_acc:.4f}")

    return history


models = {
    "Base": MLP(dropout=0.0, batchnorm=False),
    "Dropout": MLP(dropout=0.4, batchnorm=False),
    "BatchNorm": MLP(dropout=0.0, batchnorm=True),
    "Full": MLP(dropout=0.4, batchnorm=True)
}

results = {}

for name, model in models.items():
    print("\n====================", name, "====================")
    results[name] = train_model(model)


plt.figure(figsize=(10,6))

for name, res in results.items():
    plt.plot(res["loss"], label=name)

plt.title("Comparación de Loss (Train)")
plt.xlabel("Épocas")
plt.ylabel("Loss")
plt.legend()
plt.grid()
plt.show()


plt.figure(figsize=(10,6))

for name, res in results.items():
    plt.plot(res["acc"], label=name)

plt.title("Comparación de Accuracy (Train)")
plt.xlabel("Épocas")
plt.ylabel("Accuracy")
plt.legend()
plt.grid()
plt.show()


summary = []

for name, res in results.items():
    summary.append([
        name,
        res["acc"][-1],
        res["val_acc"][-1],
        res["loss"][-1],
        res["val_loss"][-1]
    ])

df_summary = pd.DataFrame(summary, columns=[
    "Modelo",
    "Train Acc",
    "Val Acc",
    "Train Loss",
    "Val Loss"
])

print(df_summary)


print("\nINTERPRETACIÓN FINAL:")

print("Base: alto sobreajuste y menor estabilidad.")
print("Dropout: reduce overfitting apagando neuronas aleatoriamente.")
print("BatchNorm: estabiliza gradientes y acelera convergencia.")
print("Full: mejor generalización y menor gap train/val.")

print("\nCONCLUSIÓN:")
print("La combinación BatchNorm + Dropout es la configuración óptima para este dataset.")

"""Bloque 5"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

print("BLOQUE 5 - MODELOS DE ENSAMBLE Y BENCHMARKING vs. MLP")

X_train_scaled = np.load('X_train_scaled_checkpoint.npy')
y_train_raw    = np.load('y_train_checkpoint.npy')
X_test_scaled  = np.load('X_test_scaled_checkpoint.npy')
y_test_raw     = np.load('y_test_checkpoint.npy')

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train_raw)
y_test  = label_encoder.transform(y_test_raw)
class_names = [str(c) for c in label_encoder.classes_]
num_classes = len(class_names)

print(f"Train: {X_train_scaled.shape} | Test: {X_test_scaled.shape} | Clases: {num_classes}")

print("\n[Ensamble 1] Random Forest — búsqueda de hiperparámetros...")
rf_grid = {
    'n_estimators': [200, 400],
    'max_depth': [None, 10, 20],
    'min_samples_leaf': [1, 3]
}
rf_search = GridSearchCV(
    RandomForestClassifier(random_state=42, class_weight='balanced', n_jobs=-1),
    rf_grid, scoring='f1_macro', cv=3, n_jobs=-1
)
t0 = time.time()
rf_search.fit(X_train_scaled, y_train)
t_rf_train = time.time() - t0
rf_model = rf_search.best_estimator_
print(f"  Mejor configuración RF: {rf_search.best_params_}")
print(f"  Tiempo de entrenamiento (incl. búsqueda): {t_rf_train:.2f}s")

tiempos_rf = []
for _ in range(5):
    t0 = time.time()
    y_pred_rf = rf_model.predict(X_test_scaled)
    tiempos_rf.append(time.time() - t0)
t_rf_inf = float(np.mean(tiempos_rf))
y_proba_rf = rf_model.predict_proba(X_test_scaled)

f1_rf_macro = f1_score(y_test, y_pred_rf, average='macro')
f1_rf_weighted = f1_score(y_test, y_pred_rf, average='weighted')
print(f"  F1-macro: {f1_rf_macro:.4f} | F1-weighted: {f1_rf_weighted:.4f}")

print("\n[Ensamble 2] XGBoost — búsqueda de hiperparámetros...")
xgb_grid = {
    'n_estimators': [200, 400],
    'max_depth': [4, 6],
    'learning_rate': [0.05, 0.1]
}
xgb_search = GridSearchCV(
    xgb.XGBClassifier(objective='multi:softprob', num_class=num_classes,
                       eval_metric='mlogloss', random_state=42,
                       n_jobs=1),
    xgb_grid, scoring='f1_macro', cv=3, n_jobs=-1
)
t0 = time.time()
xgb_search.fit(X_train_scaled, y_train)
t_xgb_train = time.time() - t0
xgb_model = xgb_search.best_estimator_
print(f"  Mejor configuración XGB: {xgb_search.best_params_}")
print(f"  Tiempo de entrenamiento (incl. búsqueda): {t_xgb_train:.2f}s")

tiempos_xgb = []
for _ in range(5):
    t0 = time.time()
    y_pred_xgb = xgb_model.predict(X_test_scaled)
    tiempos_xgb.append(time.time() - t0)
t_xgb_inf = float(np.mean(tiempos_xgb))
y_proba_xgb = xgb_model.predict_proba(X_test_scaled)

f1_xgb_macro = f1_score(y_test, y_pred_xgb, average='macro')
f1_xgb_weighted = f1_score(y_test, y_pred_xgb, average='weighted')
print(f"  F1-macro: {f1_xgb_macro:.4f} | F1-weighted: {f1_xgb_weighted:.4f}")

print("\n[MLP de referencia] Reentrenando configuración óptima de Bloque 4...")
torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)
X_test_tensor  = torch.tensor(X_test_scaled, dtype=torch.float32)

train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=64, shuffle=True)
input_dim = X_train_tensor.shape[1]

class MLPReferencia(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256), nn.BatchNorm1d(256), nn.ReLU(), nn.Dropout(0.4),
            nn.Linear(256, 128), nn.BatchNorm1d(128), nn.ReLU(), nn.Dropout(0.4),
            nn.Linear(128, 64), nn.ReLU(),
            nn.Linear(64, num_classes)
        )
    def forward(self, x):
        return self.model(x)

mlp_ref = MLPReferencia().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(mlp_ref.parameters(), lr=0.001)

for epoch in range(25):
    mlp_ref.train()
    for X_b, y_b in train_loader:
        X_b, y_b = X_b.to(device), y_b.to(device)
        optimizer.zero_grad()
        loss = criterion(mlp_ref(X_b), y_b)
        loss.backward()
        optimizer.step()

mlp_ref.eval()
tiempos_mlp = []
with torch.no_grad():
    for _ in range(5):
        t0 = time.time()
        logits = mlp_ref(X_test_tensor.to(device))
        tiempos_mlp.append(time.time() - t0)
    proba_mlp = torch.softmax(logits, dim=1).cpu().numpy()
    y_pred_mlp = np.argmax(proba_mlp, axis=1)
t_mlp_inf = float(np.mean(tiempos_mlp))

f1_mlp_macro = f1_score(y_test, y_pred_mlp, average='macro')
f1_mlp_weighted = f1_score(y_test, y_pred_mlp, average='weighted')
print(f"  F1-macro: {f1_mlp_macro:.4f} | F1-weighted: {f1_mlp_weighted:.4f}")

tabla_f1 = pd.DataFrame([
    {'Modelo': 'MLP (BatchNorm+Dropout)', 'F1-macro': f1_mlp_macro, 'F1-weighted': f1_mlp_weighted},
    {'Modelo': 'Random Forest',           'F1-macro': f1_rf_macro,  'F1-weighted': f1_rf_weighted},
    {'Modelo': 'XGBoost',                 'F1-macro': f1_xgb_macro, 'F1-weighted': f1_xgb_weighted},
]).sort_values('F1-macro', ascending=False).reset_index(drop=True)

print("\nTabla comparativa F1 — MLP vs. Ensambles:\n")
print(tabla_f1.to_string(index=False))

fig, axes = plt.subplots(1, 3, figsize=(19, 5.5))
for ax, y_pred, titulo in zip(axes, [y_pred_mlp, y_pred_rf, y_pred_xgb], ['MLP', 'Random Forest', 'XGBoost']):
    cm = confusion_matrix(y_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, xticklabels=class_names, yticklabels=class_names, cbar=False)
    ax.set_title(titulo)
plt.tight_layout()
plt.show()

mejor_nombre = 'XGBoost' if f1_xgb_macro >= f1_rf_macro else 'Random Forest'
y_pred_best = y_pred_xgb if mejor_nombre == 'XGBoost' else y_pred_rf
y_proba_best = y_proba_xgb if mejor_nombre == 'XGBoost' else y_proba_rf

print(f"\nMejor ensamble por F1-macro: {mejor_nombre}")

"""Bloque 6"""

print("BLOQUE 6 - MLOPS: TRADE-OFFS Y POLÍTICA DE UMBRALES")

n_test = len(y_test)
tabla_tradeoff = pd.DataFrame([
    {'Modelo': 'MLP',           'F1-macro': f1_mlp_macro, 'Latencia total (s)': t_mlp_inf,
     'Latencia/muestra (ms)': 1000 * t_mlp_inf / n_test},
    {'Modelo': 'Random Forest', 'F1-macro': f1_rf_macro,  'Latencia total (s)': t_rf_inf,
     'Latencia/muestra (ms)': 1000 * t_rf_inf / n_test},
    {'Modelo': 'XGBoost',       'F1-macro': f1_xgb_macro, 'Latencia total (s)': t_xgb_inf,
     'Latencia/muestra (ms)': 1000 * t_xgb_inf / n_test},
])
print("\n[+] Tabla de compromiso costo computacional vs. rendimiento:\n")
print(tabla_tradeoff.to_string(index=False))
tabla_tradeoff.to_csv('tabla_tradeoff_costo_rendimiento.csv', index=False)

plt.figure(figsize=(7.5, 5))
colores = ['#C1272D', '#003087', '#2ca02c']
plt.scatter(tabla_tradeoff['Latencia/muestra (ms)'], tabla_tradeoff['F1-macro'],
            s=160, c=colores)
for i, row in tabla_tradeoff.iterrows():
    plt.annotate(row['Modelo'], (row['Latencia/muestra (ms)'], row['F1-macro']),
                 textcoords="offset points", xytext=(10, 6))
plt.xlabel("Latencia por muestra (ms)")
plt.ylabel("F1-macro (test)")
plt.title("Compromiso costo computacional vs. rendimiento analítico")
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.savefig('tradeoff_costo_rendimiento.png', dpi=150, bbox_inches='tight')
plt.show()



def zona_riesgo(p):
    if p >= 0.85:
        return 'Confianza (>=85%)'
    elif p >= 0.40:
        return 'Incertidumbre (40-85%)'
    else:
        return 'Rechazo (<40%)'

orden_zonas = ['Confianza (>=85%)', 'Incertidumbre (40-85%)', 'Rechazo (<40%)']

def analizar_zonas(y_proba, y_pred, etiqueta):
    p_max = y_proba.max(axis=1)
    zonas = np.array([zona_riesgo(p) for p in p_max])
    conteo = pd.Series(zonas).value_counts().reindex(orden_zonas).fillna(0).astype(int)
    print(f"\n Política de zonas usando probabilidades de: {etiqueta}")
    print(f"    Probabilidad máxima observada en todo el test: {p_max.max():.3f}")
    print(conteo.to_string())
    print("    Porcentaje del test en cada zona:")
    print((100 * conteo / len(zonas)).round(1).to_string())
    print("    Validación empírica (exactitud real dentro de cada zona):")
    for z in orden_zonas:
        mask = zonas == z
        if mask.sum() > 0:
            acc_z = accuracy_score(y_test[mask], y_pred[mask])
            print(f"      [{z}]: {acc_z:.3f}  (n={mask.sum()})")
        else:
            print(f"      [{z}]: zona vacía (n=0)")
    return conteo, p_max

conteo_best, p_max_best = analizar_zonas(y_proba_best, y_pred_best, mejor_nombre)
conteo_mlp, p_max_mlp = analizar_zonas(proba_mlp, y_pred_mlp, 'MLP')

plt.figure(figsize=(8, 5))
plt.hist(p_max_best, bins=20, alpha=0.6, label=mejor_nombre, color='#003087')
plt.hist(p_max_mlp, bins=20, alpha=0.6, label='MLP', color='#C1272D')
plt.axvline(0.85, color='green', linestyle='--', label='Umbral 85%')
plt.axvline(0.40, color='orange', linestyle='--', label='Umbral 40%')
plt.xlabel("Probabilidad máxima predicha por muestra")
plt.ylabel("N° de muestras (test)")
plt.title("Distribución de confianza predictiva: ensamble vs. MLP")
plt.legend()
plt.tight_layout()
plt.savefig('distribucion_confianza_modelos.png', dpi=150, bbox_inches='tight')
plt.show()


conteo_zonas, p_max, zonas = conteo_best, p_max_best, np.array(
    [zona_riesgo(p) for p in p_max_best])

plt.figure(figsize=(7.5, 4.5))
sns.barplot(x=conteo_zonas.index, y=conteo_zonas.values,
            palette=['#2ca02c', '#e6b800', '#d62728'])
plt.title(f"Distribución de detecciones por zona operativa — {mejor_nombre}")
plt.xlabel("Zona operativa")
plt.ylabel("N° de registros (test)")
plt.xticks(rotation=10)
plt.tight_layout()
plt.savefig('distribucion_zonas_riesgo.png', dpi=150, bbox_inches='tight')
plt.show()